import React from 'react'
import { Link } from 'react-router-dom'
import { PageHeader, Section, Prose, Callout, Ref, Table, StatGrid, Stat, CardGrid, Card, Steps, Figure, LayerStack, DefList, Badge } from '../components/ui.jsx'

export default function Car2Car() {
  return (
    <article>
      <PageHeader
        kicker="Vehicle Industry"
        title="CAR 2 CAR Communication Consortium"
        intro="The CAR 2 CAR Communication Consortium (C2C-CC) is the vehicle-industry side of European C-ITS — a non-commercial association of vehicle manufacturers, Tier-1 suppliers, and research organisations that defines exactly what a car, truck, motorcycle or e-bike must do to participate in Europe's cooperative road-safety system. Its master specification, the Basic System Profile (BSP), pins down every interoperability requirement from antenna power to authorization-ticket rotation, so vehicles from competing brands communicate seamlessly the moment they leave the factory."
        sources={['C2CCC RS 2035', 'C2CCC RS 2036', 'C2CCC RS 2037', 'C2CCC TR 2000', 'C2CCC WP 2072']}
      />

      {/* ── 1. What is C2C-CC ─────────────────────────────────────────────── */}
      <Section id="what-is-c2c-cc" title="What is the C2C-CC?">
        <p>
          Founded in 2002 by vehicle manufacturers who believed cooperative road traffic could save lives, the
          CAR 2 CAR Communication Consortium (C2C-CC) is today the authoritative voice of the automotive
          industry in European Cooperative Intelligent Transport Systems (C-ITS). Its members include worldwide
          major vehicle manufacturers (OEMs), equipment suppliers, and research organisations.
        </p>
        <p>
          The consortium's primary objective is to ensure <strong>interoperability</strong> in C-ITS between
          different vehicle manufacturers and with road infrastructure — an engineering challenge that means
          every car, truck, bus, motorcycle, e-bike, and even agricultural machine carrying a C-ITS station
          must transmit and receive in a mutually intelligible way regardless of make, model, or country of
          sale. C2C-CC members focus on wireless Vehicle-to-Vehicle (V2V) communication based on the
          Direct Communication paradigm (no cloud intermediate required), with Vehicle-to-Infrastructure (V2I)
          as an equally important companion.
        </p>

        <Callout type="key" title="Core mandate">
          C2C-CC specifies the <em>vehicle side</em> of European C-ITS. Its counterpart for the road side is
          the <Link to="/c-roads">C-Roads platform</Link>. Together they form the two pillars of European
          interoperability: OEM-specified vehicle stations meeting infrastructure-specified roadside stations.
        </Callout>

        <StatGrid cols={3}>
          <Stat value="2002" label="Founded" sub="by European vehicle OEMs" />
          <Stat value="ITS-G5" label="Primary radio technology" sub="5 855–5 925 MHz band" />
          <Stat value="500 000+" label="C-ITS-equipped vehicles" sub="commercially deployed by 2022" />
        </StatGrid>
      </Section>

      {/* ── 2. Ecosystem relationships ─────────────────────────────────────── */}
      <Section id="relationships" title="Relationships: ETSI, C-Roads and EU Policy">
        <p>
          C2C-CC does not write standards in isolation — it feeds into and draws from a wider ecosystem:
        </p>

        <DefList items={[
          {
            term: 'ETSI TC ITS',
            def: 'The European Telecommunications Standards Institute\'s ITS technical committee produces the normative standards (EN 302 xxx, TS 103 xxx) that C2C-CC profiles and mandates. C2C-CC members contribute heavily to ETSI work items, ensuring that ETSI standards reflect what automotive OEMs actually need to build deployable products.'
          },
          {
            term: 'C-Roads platform',
            def: (
              <>
                <Link to="/c-roads">C-Roads</Link> is the road-operator equivalent — national transport ministries
                and road authorities specifying what a roadside C-ITS station (RSU) must do. C2C-CC and C-Roads
                work under a signed Memorandum of Understanding to harmonise their specifications so that vehicle
                CAMs and DENMs generated by the BSP profile are correctly understood by roadside stations, and
                vice versa.
              </>
            )
          },
          {
            term: 'EU policy',
            def: (
              <>
                The <Link to="/eu-policy">EU ITS Directive</Link> (2010/40/EC and amendments), the Amsterdam
                Declaration on cooperative and automated driving, and the European Commission's C-ITS strategy
                all lean on C2C-CC and C-Roads work as the technical foundation. The C2C-CC BSP was referenced
                in draft EU delegated acts on C-ITS deployment.
              </>
            )
          },
          {
            term: 'EuroNCAP',
            def: 'The independent vehicle safety assessment body has already recognised the C-ITS Day-1 local hazard warning application in its safety ratings and included C-ITS in its long-term 2025 and 2027 roadmaps — creating a market pull for BSP-compliant vehicles.'
          }
        ]} />

        <Figure caption="C2C-CC sits at the centre of the vehicle-industry C-ITS ecosystem, feeding requirements upward to ETSI standardisation and coordinating horizontally with C-Roads on I2V interoperability.">
          <div className="flex flex-col items-center gap-2 py-4">
            <div className="flex gap-4">
              <div className="rounded border border-amber-500 bg-amber-950 px-4 py-2 text-amber-200 text-sm font-semibold">EU Policy / EuroNCAP</div>
              <div className="rounded border border-amber-500 bg-amber-950 px-4 py-2 text-amber-200 text-sm font-semibold">ETSI TC ITS (standards)</div>
            </div>
            <div className="text-slate-500 text-xs">&#8597; requirements / profiles</div>
            <div className="flex gap-6 items-center">
              <div className="rounded border-2 border-brand-400 bg-brand-950 px-6 py-3 text-brand-200 text-sm font-bold">C2C-CC (vehicle BSP)</div>
              <div className="text-slate-500 text-xs">&#8596; MoU / harmonisation</div>
              <div className="rounded border-2 border-emerald-400 bg-emerald-950 px-6 py-3 text-emerald-200 text-sm font-bold">C-Roads (road RSU)</div>
            </div>
            <div className="text-slate-500 text-xs">&#8595; deployed products</div>
            <div className="flex gap-4">
              <div className="rounded border border-slate-500 bg-ink-900 px-4 py-2 text-slate-300 text-sm">OEM vehicles (BSP)</div>
              <div className="rounded border border-slate-500 bg-ink-900 px-4 py-2 text-slate-300 text-sm">Road-side units (C-Roads)</div>
            </div>
          </div>
        </Figure>
      </Section>

      {/* ── 3. Basic System Profile (BSP) overview ─────────────────────────── */}
      <Section id="bsp-overview" title="The Basic System Profile (BSP)">
        <p>
          The BSP is C2C-CC's master specification — a release bundle of interconnected documents that together
          define the minimum interoperable vehicle C-ITS system. The BSP does three things: it names the ETSI
          (and other) standards that apply; it <em>profiles</em> those standards (selecting specific options,
          forbidding others); and it adds concrete implementation requirements where the standards leave room
          for variation.
        </p>
        <p>
          The BSP is structured as a three-layer requirement hierarchy mirroring the abstraction levels from
          goals down to testable behaviour:
        </p>

        <Steps>
          <div>
            <strong>Objectives (RS 2035)</strong> — abstract, non-testable goals such as "improve road safety
            towards Vision Zero" or "protect privacy under GDPR". Each objective is further detailed by one or
            more features or feature requests.
          </div>
          <div>
            <strong>Features (RS 2036)</strong> — desired abilities of the vehicle C-ITS station. For example,
            "provide services for communicating with other C-ITS stations using the vehicular ad-hoc RLAN in
            5 855–5 925 MHz" or "implement backward-compatible facility-layer services and messages". A feature
            is assumed tested when all its detailing requirements are tested.
          </div>
          <div>
            <strong>Vehicle C-ITS Station Profile (RS 2037)</strong> — the lowest level: concrete, testable
            requirements with numeric parameters. This is where interoperability actually lives — RF power,
            GeoNetworking field values, CAM generation rates, ECDSA key sizes, authorization-ticket rotation
            distances, clock tolerances.
          </div>
        </Steps>

        <Callout type="info" title="Backward compatibility is a first-class requirement">
          RS_OBJ_00440 mandates that every Release 2 vehicle C-ITS station is backward compatible with Release 1
          stations and C-Roads Release 2.x.y — a newer vehicle must provide at least the same service level as
          an older one in an older environment, and older vehicles must retain full functionality in a
          newer-release environment.
        </Callout>

        <CardGrid cols={3}>
          <Card title="RS 2035 — Objectives" accent="brand">
            Sets the abstract "why": Vision Zero, ad-hoc low-latency local comms, GDPR privacy, misbehaviour
            detection, functional safety, EU-wide trusted network. Objectives detail the full vehicle type
            scope: cars, trucks, buses, PTWs, e-bikes, cycles, agricultural machines, rail vehicles.
          </Card>
          <Card title="RS 2036 — Features" accent="amber">
            Specifies the "what": multi-channel radio access, DCC congestion avoidance, CEN-DSRC interference
            mitigation, CAM/DENM facility services, CPM perception sharing, GNSS + confidence information,
            certificate-based authentication, AT pseudonym rotation, misbehaviour reporting, ASIL safety
            containers.
          </Card>
          <Card title="RS 2037 — Profile" accent="emerald">
            Defines the "how" with numeric requirements: G5-SCH0 at 5 900 MHz (6 Mbit/s default), CAM on
            Single Hop Broadcast, DENM on GeoBroadcast, GN address anonymous mode, ECDSA P-256 signatures,
            AT rotation every 800–1 500 m then 10–20 km then 25–35 km intervals, clock valid within 20 ms
            of C-ITS time (TAI since 2004-01-01), RF power 17–33 dBm e.i.r.p.
          </Card>
          <Card title="Triggering Conditions (RS 200x)" accent="violet">
            Per-use-case requirement documents specifying how the vehicle detects an event (which CAN signals,
            which sensor thresholds) and how to populate DENM fields. Covers Adverse Weather, Dangerous
            Situation, Stationary Vehicle, Special Vehicle, Traffic Condition, Unresponsive Driver,
            Wrong-way Driver, Exchange of IRCs.
          </Card>
          <Card title="Protection Profiles (PP 2056, 2302)" accent="rose">
            Common Criteria security evaluation targets. PP 2056 covers the V2X Hardware Security Module
            (HSM); PP 2302 covers the full Vehicle C-ITS Station (VCS). Provide the formal security assurance
            framework on top of ETSI PKI requirements.
          </Card>
          <Card title="Supporting documents" accent="cyan">
            TR 2000 Release Overview, TR 2053 Glossary, TR 2086 Conventions, TR 2052 References, TR 2305
            DENM Mapping (to DATEX II / TPEG), TR 2309 Assessment Sheet and TR 2310 Assessment Guide for
            conformity evaluation.
          </Card>
        </CardGrid>
      </Section>

      {/* ── 4. BSP document inventory ──────────────────────────────────────── */}
      <Section id="bsp-documents" title="BSP Release 2.0.2 Document Inventory">
        <p>
          Release 2.0.2 (December 2025) is the current public release. Every deliverable is shown below with
          its document type and role in the bundle.
        </p>
        <Table
          headers={['UID', 'Abbrev.', 'Type', 'Long Name', 'Key Content']}
          rows={[
            ['2000', 'RelOv', <Badge tone="cyan">TR</Badge>, 'Release Overview', 'Index of all deliverables; change history per document'],
            ['2002', 'tcAdWe', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Adverse Weather', 'DENM triggers for icy roads, reduced visibility, fog'],
            ['2003', 'tcDaSi', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Dangerous Situation', 'Emergency brake, pre-crash, collision-imminent events'],
            ['2004', 'tcIRC', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Exchange of IRCs', 'In-Road Character (road condition) DENM data quality'],
            ['2005', 'tcSpVe', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Special Vehicle Warning', 'Emergency vehicles, road-works trailers, priority vehicles'],
            ['2006', 'tcStVe', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Stationary Vehicle Warning', 'Broken-down / stationary vehicle DENM triggering'],
            ['2007', 'tcTrJa', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Traffic Condition', 'Slow traffic / traffic-jam tail DENM'],
            ['2035', 'OBJ', <Badge tone="brand">RS</Badge>, 'Objectives', 'Abstract requirements — Vision Zero, privacy, misbehaviour, ASIL'],
            ['2036', 'FEA', <Badge tone="brand">RS</Badge>, 'Features', 'Vehicle C-ITS station abilities — radio access, services, security'],
            ['2037', 'BSP', <Badge tone="brand">RS</Badge>, 'Vehicle C-ITS Station Profile', 'Concrete testable requirements with numeric parameters'],
            ['2052', 'Refs', <Badge tone="cyan">TR</Badge>, 'Reference List', 'Normative and informative references for all documents'],
            ['2053', 'Glos', <Badge tone="cyan">TR</Badge>, 'Glossary', 'C2C-CC terminology definitions'],
            ['2056', 'HSM', <Badge tone="rose">PP</Badge>, 'Protection Profile — V2X Hardware Security Module', 'Common Criteria evaluation target for HSM chips'],
            ['2086', 'ConV', <Badge tone="cyan">TR</Badge>, 'Conventions Used', 'Requirement notation, MoSCoW levels, tagging conventions'],
            ['2302', 'VCS', <Badge tone="rose">PP</Badge>, 'Protection Profile — Vehicle C-ITS Station', 'CC evaluation target for the full station software/hardware'],
            ['2305', 'DENMM', <Badge tone="cyan">TR</Badge>, 'DENM Mapping', 'Cross-mapping DENM &#8596; DATEX II &#8596; TPEG message formats'],
            ['2309', 'AS', <Badge tone="cyan">TR</Badge>, 'Assessment Sheet', 'Conformity assessment sheet for C-ITS standards'],
            ['2310', 'AG', 'WP', 'Assessment Guide', 'Guide for conformity assessment process'],
            ['2311', 'AT', <Badge tone="cyan">TR</Badge>, 'Assessment Declaration Template', 'Template for OEM conformity declarations'],
            ['2321', 'URD', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Unresponsive Driver', 'DENM for vehicles with incapacitated driver'],
            ['2322', 'WWD', <Badge tone="violet">RS</Badge>, 'Triggering Cond. — Wrong-way Driver', 'Ghost-driver detection and DENM triggering'],
          ]}
          caption="C2C-CC BSP Release 2.0.2 deliverables (TR = Technical Report, RS = Requirements Specification, PP = Protection Profile, WP = White Paper)"
        />
      </Section>

      {/* ── 5. Day-1 safety use cases ──────────────────────────────────────── */}
      <Section id="day1-use-cases" title="Day-1 Safety Use Cases">
        <p>
          The C2C-CC roadmap organises deployment in phases named Day 1, Day 2, and Day 3+. Day 1 — the
          current live phase — is called <strong>Awareness Driving</strong>: vehicles transmit their own status
          and event-triggered hazard warnings to increase the spatial and temporal awareness horizon for
          drivers and vehicle systems. All Day-1 vehicle-originated use cases rely on two ETSI facility-layer
          services:
        </p>
        <ul>
          <li>
            <strong>Cooperative Awareness Service (CA)</strong> — generates <Link to="/cam">CAMs</Link> at
            1–10 Hz adaptively based on vehicle dynamics and channel load; Single Hop Broadcast (SHB).
          </li>
          <li>
            <strong>Decentralised Environmental Notification Service (DEN)</strong> — generates{' '}
            <Link to="/denm">DENMs</Link> on event detection; GeoBroadcast (GBC), multi-hop over the
            relevance area, repeated as long as the event is valid.
          </li>
        </ul>

        <Table
          headers={['Use Case', 'Triggering Document', 'Message(s)', 'Notes']}
          rows={[
            ['Stationary Vehicle Warning', 'RS 2006 (tcStVe)', 'DENM', 'Broken-down vehicle, accident stopped; speed ≤ 0.08 m/s for cars, ≤ 1.4 m/s for PTW'],
            ['Slow Vehicle / Traffic-Jam Warning', 'RS 2007 (tcTrJa)', 'DENM', 'Tail-of-queue approaching warning; relative speed delta detection'],
            ['Adverse Weather Conditions', 'RS 2002 (tcAdWe)', 'DENM', 'Icy road, low visibility, reduced friction detected by ESC / rain sensor'],
            ['Dangerous Situation (Emergency Brake)', 'RS 2003 (tcDaSi)', 'DENM', 'Emergency brake (eCall trigger), pre-crash imminent collision alert'],
            ['Special / Emergency Vehicle Warning', 'RS 2005 (tcSpVe)', 'DENM', 'Blue-light vehicles, roadworks vehicles, road-operator trailers'],
            ['Wrong-way Driver (Ghost Driver)', 'RS 2322 (tcWWD)', 'DENM', 'Counter-flow driving on motorway detected by heading vs lane map'],
            ['Unresponsive Driver', 'RS 2321 (tcURD)', 'DENM', 'Vehicle driving erratically; triggers eCall assistance chain'],
            ['Motorcycle Approaching Information (MAI)', 'CAM profile (PTW)', 'CAM', 'Day-1 PTW presence beaconing using existing CAM format'],
            ['Exchange of In-Road Characters (IRC)', 'RS 2004 (tcIRC)', 'DENM', 'Road surface condition sharing (wetness, ice, debris)'],
            ['In-Vehicle Signage / GLOSA (received)', 'C-Roads SPATEM/MAPEM', 'SPATEM, MAPEM, IVIM', 'Infrastructure → vehicle; vehicle BSP profiles the receive side'],
          ]}
          caption="Day-1 C-ITS safety and efficiency use cases as defined by C2C-CC BSP triggering-condition documents"
        />

        <Callout type="tip" title="Use-case triggering is transmitter-side; applications are receiver-side">
          The BSP and triggering-condition documents define exactly how a vehicle detects and announces an
          event — which CAN signals to monitor, which thresholds to apply, how to fill DENM fields. What the
          receiving vehicle does with that information (warn the driver, apply autonomous braking, update a
          map) is intentionally left to the OEM to allow competitive differentiation while maintaining liability
          clarity.
        </Callout>
      </Section>

      {/* ── 6. BSP technical parameters ───────────────────────────────────── */}
      <Section id="bsp-params" title="Key Technical Parameters (RS 2037 Profile)">
        <p>
          The Vehicle C-ITS Station Profile (RS 2037) contains a normative parameter table (Table 3 in the
          document) that fixes concrete numeric values for the entire protocol stack. Key parameters:
        </p>

        <Table
          headers={['Parameter', 'Value', 'Unit', 'Meaning']}
          rows={[
            ['G5-SCH0 (primary channel)', '5 900 MHz, ch. 180', 'MHz', 'Default service channel for CAMs and priority C-ITS services'],
            ['pAlDataRateSch0', '6', 'Mbit/s', 'Default data rate on SCH0; range 3–27 Mbit/s'],
            ['RF output power target', '23 (range 17–33)', 'dBm e.i.r.p.', 'Nominal transmit power; max 33 dBm with ≥30 dB TPC range'],
            ['pPotiMaxTimeDiff', '20', 'ms', 'Max offset between station clock and C-ITS TAI time'],
            ['pPotiUpdateRate', '10', 'Hz', 'GNSS position-and-time update rate'],
            ['pCamGenNumber', '3', 'msgs', 'CAMs that may be generated without time-interval restrictions'],
            ['pCamPathMaxLength / MinLength', '500 / 200', 'm', 'Bounds on CAM path history length'],
            ['pDenmTraceMaxLength / MinLength', '1 000 / 600', 'm', 'Bounds on DENM trace path length'],
            ['pDenmTraceMaxPoints', '40', 'points', 'Max trace points in DENMs'],
            ['pGnMaxAreaSize', '80', 'km²', 'Maximum GeoNetworking GeoBroadcast area size'],
            ['pSecMaxAcceptDistance', '10', 'km', 'Max sender–receiver distance for message acceptance (6 hops \xd7 1 km)'],
            ['pSecCamPastToleranceTime', '2', 's', 'Max age of CAM timestamp accepted at receiver'],
            ['pSecMessagePastToleranceTime', '10', 'min', 'Max age of non-CAM message timestamp accepted'],
            ['pSecMaxPreloadTime', '3', 'months', 'Max AT preload time (2 weeks for aftermarket supervised OBUs)'],
            ['AT rotation #1 (after ignition on)', '800–1 500', 'm', 'First pseudonym change; random in range'],
            ['AT rotation #2', '10 000–20 000', 'm', 'Second rotation interval'],
            ['AT rotation #3+ (steady state)', '25 000–35 000', 'm', 'Subsequent steady-state pseudonym rotation interval'],
            ['Min. AT pool for signing', '56', 'ATs', 'Must hold ≥56 valid ATs + private keys before signing any message'],
            ['pSecChangeBlockingMaxTime', '5', 'min', 'Max time an application can delay AT rotation while vehicle moves'],
            ['GN address mode', 'ANONYMOUS (2)', '—', 'GN source address configured anonymously for privacy (pGnAddrConfMode)'],
            ['pGnEtherType', '0x8947', '—', 'EtherType for GeoNetworking frames'],
            ['pBtpCamPort', '2 001', '—', 'Well-known BTP destination port for CAM'],
            ['pBtpDenmPort', '2 002', '—', 'Well-known BTP destination port for DENM'],
          ]}
          caption="Selected normative parameters from C2C-CC RS 2037 BSP Release 2.0.2"
        />

        <Callout type="info" title="Authorization ticket rotation and privacy">
          The AT rotation protocol is specifically engineered to prevent vehicle tracking. A new random
          Authorization Ticket (AT pseudonym certificate) is selected from a pool of at least 56 at every
          ignition restart (after at least 10 min off), then again after 800–1 500 m, then at 10–20 km, and
          thereafter every 25–35 km of travel. At each rotation, the GN source address, DENM trace storage,
          CAM path history, and all transmitted identifiers are simultaneously replaced to defeat correlation
          attacks. See <Link to="/security">Security</Link> for the full CCMS architecture.
        </Callout>
      </Section>

      {/* ── 7. Roadmap: Day 1 → Day 2 → Day 3+ ───────────────────────────── */}
      <Section id="roadmap" title="C2C-CC Deployment Roadmap: Day 1 to Day 3+">
        <p>
          The C2C-CC organises the evolution of C-ITS into successive deployment phases. Each phase inherits
          all capabilities of the previous phase in a backward-compatible manner — newer vehicles continue to
          transmit information needed by older vehicles. New services and supporting functionalities are layered
          on top, not replacing them.
        </p>

        <CardGrid cols={3}>
          <Card title="Day 1 — Awareness Driving" accent="emerald" icon="👁️">
            <p className="text-sm">
              <strong>Now live.</strong> Vehicles share their own dynamics (CAM at 1–10 Hz) and hazard alerts
              (DENM). Infrastructure supplies SPATEM/MAPEM and IVIM. Applications warn drivers of hazards
              beyond line of sight. First deployed: VW Golf 8 in 2019; 500 000+ vehicles and 20 000 km of
              roads equipped by 2022.
            </p>
            <p className="text-sm mt-1 text-slate-400">Services: CA (CAM), DEN (DENM), TLM, RLT, IVI</p>
          </Card>
          <Card title="Day 2 — Sensing Driving" accent="amber" icon="📡">
            <p className="text-sm">
              <strong>Standards in progress.</strong> Vehicles with environment sensors (radar, lidar, camera)
              share detected objects via <Link to="/cpm">CPM</Link> and VRU alerts via{' '}
              <Link to="/vam">VAM</Link>. Enables awareness of non-equipped road users (pedestrians, cyclists)
              around corners. Semi-automated reactions (cooperative emergency braking, C-ACC) become possible.
              Requires CPM object quality metrics, functional-safety ASIL containers, and misbehaviour
              detection.
            </p>
            <p className="text-sm mt-1 text-slate-400">New services: CP (CPM), VRU Awareness (VAM)</p>
          </Card>
          <Card title="Day 3+ — Cooperative Driving" accent="violet" icon="🤖">
            <p className="text-sm">
              <strong>R&amp;D phase.</strong> SAE Level 3–4 automated vehicles share trajectories and
              coordinate manoeuvres (cooperative lane change, merging, advanced C-ACC). Infrastructure may
              provide trajectory suggestions, gap advisories, minimum-risk-manoeuvre notifications, and
              valet-parking guidance. VRUs become active V2X participants.{' '}
              <Link to="/mcm">MCM / Manoeuvre Coordination</Link> is a key enabler.
            </p>
            <p className="text-sm mt-1 text-slate-400">New services: MCM, IMZM, advanced SPATEM</p>
          </Card>
        </CardGrid>

        <Callout type="tip" title="The ISAD framework for infrastructure readiness">
          The roadmap uses the Infrastructure Support Levels for Automated Driving (ISAD) to classify road
          infrastructure capability at each phase. ISAD Level C (static and dynamic road info for human
          drivers) maps to Day 1; higher ISAD levels providing perception data and trajectory guidance map
          to Day 2 and Day 3+ respectively.
        </Callout>
      </Section>

      {/* ── 8. White-paper programme ───────────────────────────────────────── */}
      <Section id="white-papers" title="White-Paper Programme">
        <p>
          Alongside the normative BSP, C2C-CC publishes an extensive series of white papers, working papers,
          and technical reports that explore specific technical challenges, propose solutions, and feed
          future BSP releases. The breadth of topics spans the full stack from RF physics to automated-driving
          coordination:
        </p>

        <Table
          headers={['Document', 'Theme', 'Key Contribution']}
          rows={[
            ['WP 2072 — Day 2 and Beyond Roadmap v1.2', 'Deployment strategy', 'Canonical C2C-CC phased roadmap (Day 1/2/3+); functional development goals and enabling concepts for cooperative driving'],
            ['WP 2082/2084/2085 — MCO Requirements / Capabilities / Concept', 'Multi-Channel Operation', 'Requirements, technical capability analysis, and concept for using multiple 5.9 GHz channels simultaneously to increase throughput for CPM and future services; relates to BSP feature RS_FEA_502'],
            ['WP 2091 / WP 2096 — Co-channel Coexistence', 'Spectrum coexistence', 'Mitigation methods and additional analysis for co-channel coexistence between ITS-G5 and other 5.9 GHz radio systems'],
            ['WP 2092 — Misbehaviour Detection and Reporting', 'Security / Trust', 'Methods for vehicles to detect and report stations transmitting false or misleading information; linked to ETSI TR 103 460 definition and BSP objective RS_OBJ_00438'],
            ['WP 2098 — IEEE 802.11bd V2X Evolution', 'Physical layer evolution', 'Analysis of IEEE 802.11bd as an evolutionary upgrade to ITS-G5/802.11p; capacity improvements while maintaining backward compatibility with existing deployed devices'],
            ['WP 2087 — VRU Awareness Study', 'Vulnerable Road Users', 'Technical study on awareness requirements for pedestrians, cyclists, and PTWs in C-ITS; inputs to ETSI TS 103 300 VAM specification'],
            ['TR 2089 — CPM Object Quality', 'Collective Perception', 'Harmonised definition of object quality metrics combining confidence and accuracy levels for CPM; enables cross-vendor consistency on which objects are broadcast'],
            ['WP 2300 — Connected and Cooperative Automated Driving', 'CCAM vision', "C2C-CC's vision for how C-ITS underpins connected, cooperative and automated mobility (CCAM); role of V2X in SAE Level 3–4 operation"],
            ['WP 2303 — PTW Path Prediction', 'Powered Two-Wheelers', 'Path prediction algorithms specific to motorcycles and powered two-wheelers for inclusion in CAM and CPM messages'],
            ['WP 2099 — Lane Layout Description', 'Map / topology', 'Specification of lane layout description in C-ITS messages; ADASIS-based algorithm for deriving ETSI LanePosition from map data (codified in RS 2037 RS_BSP_576)'],
            ['WP 2312 — Truck Parking', 'Commercial vehicles', 'C-ITS-based truck parking availability notification use case and message requirements'],
            ['WP 2324 — Bicycle Safety Use Cases', 'Cycles / VRU', 'C-ITS safety use cases specifically for cyclists; e-bike and cycle CAM profiling considerations'],
            ['WP 2320 — Trustworthiness in C-ITS', 'Security', 'Holistic trustworthiness framework combining PKI, misbehaviour detection, functional safety, and data quality'],
            ['TR 2047 — Spectrum Sharing 5.9 GHz', 'Spectrum policy', 'C2C-CC position on 5.9 GHz spectrum sharing; arguments for dedicated ITS spectrum protection'],
            ['TR 2049 — ETSI ITS-G5 Channel Usage', 'Spectrum / channels', 'Channel usage analysis and recommendations for the ITS-G5 multi-channel architecture (SCH0–SCH6)'],
            ['TR 2050 — Spectrum Needs', 'Spectrum policy', 'Quantified spectrum needs analysis for current and future C-ITS use cases'],
            ['TR 2045 / TR 2051 — Personal Data Protection', 'Privacy / GDPR', 'Position papers and FAQ on C-ITS data protection; pseudonymisation, AT rotation, and GDPR Article 4 analysis'],
            ['TR 2052 — CAM Statistics Survey', 'Performance', 'Survey of real-world CAM transmission statistics from early deployments'],
            ['TR 2053 — Urban Rail Integration ITS-G5', 'Intermodal', 'Study on integrating trams and light rail as C-ITS stations using ITS-G5'],
            ['DCC Performance Analysis', 'Congestion control', 'Analysis of Decentralised Congestion Control (DCC, ETSI TS 102 687) algorithm performance in dense vehicle scenarios'],
            ['Handbook for V2X Simulation', 'Simulation', 'Guidance for consistent V2X simulation methodology for C-ITS system evaluation'],
            ['UC 2097 — Day 2 Use Cases and Beyond', 'Use cases', 'Detailed catalogue of Day 2 and Day 3+ sample use cases with associated V2X messages and message adaptations'],
            ['C-ITS Security and Privacy Position Paper (2015)', 'Security', 'Early C2C-CC paper establishing the security and privacy design principles underpinning the European CCMS architecture'],
          ]}
          caption="C2C-CC white-paper and working-paper programme — publicly available at car-2-car.org"
        />
      </Section>

      {/* ── 9. Protection Profiles ─────────────────────────────────────────── */}
      <Section id="protection-profiles" title="Protection Profiles: Common Criteria Security Evaluation">
        <p>
          Beyond operational requirements, C2C-CC publishes two Common Criteria (CC) Protection Profiles that
          define the security assurance requirements for the hardware and software components of a vehicle
          C-ITS station. These allow OEMs and suppliers to obtain independent third-party security evaluations
          against a standardised target.
        </p>

        <CardGrid cols={2}>
          <Card title="PP 2056 — V2X Hardware Security Module (HSM)" accent="rose" icon="🔐">
            <p className="text-sm">
              The Protection Profile for the V2X HSM defines security functional requirements and assurance
              level for the dedicated cryptographic hardware that stores private keys, generates ECDSA
              signatures, and manages the AT pool inside a vehicle C-ITS station. The HSM must resist physical
              tampering and logical attacks, ensuring that private keys cannot be extracted even if the
              surrounding vehicle ECU is compromised. CC evaluation against this PP provides the
              hardware-level trust anchor for the entire C-ITS PKI chain.
            </p>
          </Card>
          <Card title="PP 2302 — Vehicle C-ITS Station (VCS)" accent="rose" icon="🛡️">
            <p className="text-sm">
              The Protection Profile for the complete Vehicle C-ITS Station defines security targets for the
              full station software and hardware combination — encompassing message signing/verification,
              AT lifecycle management, privacy protection through pseudonym rotation, misbehaviour detection
              interfaces, and the secure channel between the C-ITS station and the in-vehicle network. CC
              evaluation against VCS PP provides assurance that the deployed station correctly implements
              the C2C-CC security requirements from RS 2037.
            </p>
          </Card>
        </CardGrid>

        <Callout type="info" title="Relationship to ETSI security standards">
          The Protection Profiles complement rather than replace the ETSI security standards. RS 2037
          requires compliance with the European C-ITS Certificate Policy, the C-ITS Security Policy,
          and ETSI <Ref code="TS 103 097" kind="ETSI" title="ITS security header and certificate formats" />,{' '}
          <Ref code="TS 102 940" kind="ETSI" title="ITS security architecture and management" />, and{' '}
          <Ref code="TS 102 941" kind="ETSI" title="Trust and privacy management" />. The C2C-CC PPs add
          Common Criteria methodology and an independent evaluator into the trust chain. See{' '}
          <Link to="/security">Security</Link> for the full CCMS picture.
        </Callout>
      </Section>

      {/* ── 10. Europe's Path to CCAM ──────────────────────────────────────── */}
      <Section id="ccam-vision" title="Europe's Path to CCAM">
        <p>
          C2C-CC's 2022 position paper <em>C-ITS: Europe's Path to Connected, Cooperative &amp; Automated
          Mobility</em> articulates the industry's long-term vision and policy asks. Key themes:
        </p>

        <DefList items={[
          {
            term: 'C-ITS as public infrastructure',
            def: 'C2C-CC argues that C-ITS creates a public communications infrastructure analogous to the road network itself, on which future automation depends. It is specified by those who operate it — automotive manufacturers and road operators — is based on open accessible standards, and is designed to keep licence costs at minimum.'
          },
          {
            term: 'Interoperability and backward compatibility as non-negotiables',
            def: 'The LEGO-brick metaphor: C-ITS transmitters "click" only if they follow the same specification. Backward compatibility means a plug made in 1990 works with sockets from 1965 and 2022 alike — vehicles sold today must still benefit from C-ITS infrastructure built decades from now, and vice versa.'
          },
          {
            term: 'ITS-G5 delivers Day-1 now',
            def: 'The position paper states that ITS-G5 fully delivers Day-1 use cases. Industry welcomes evolution of the physical layer (IEEE 802.11bd, potential cellular complementary technology) but insists that service continuity and backward compatibility must be preserved across any technology transition.'
          },
          {
            term: 'EuroNCAP recognition as market driver',
            def: "EuroNCAP's recognition of \"local hazard warning\" (a Day-1 ITS-G5 application) in its safety ratings creates a concrete commercial incentive for OEMs to equip vehicles with BSP-compliant C-ITS stations. EuroNCAP's 2025 and 2027 roadmaps both include C-ITS commitments."
          },
          {
            term: 'Cooperative sensing bridges the automation gap',
            def: 'Day-2 Collective Perception (CPM) allows a vehicle\'s sensors to become a shared resource for the network. An automated vehicle that "sees" a pedestrian hidden around a corner can share that perception with approaching vehicles — bridging the line-of-sight limitation that prevents purely on-board sensors from enabling higher automation levels safely.'
          },
          {
            term: 'Policy asks',
            def: 'C2C-CC calls on EU regulators to protect 5.9 GHz spectrum, maintain backward-compatibility requirements in the ITS Directive, support the European C-ITS security framework (CCMS / CPOC), and engage OEMs and road operators in the governance of the C-ITS ecosystem. See ' + 'the EU Policy page for details.'
          }
        ]} />
      </Section>

      {/* ── 11. Vehicle type coverage (R2 expansion) ───────────────────────── */}
      <Section id="vehicle-types" title="Vehicle Type Coverage: Release 2 Expansion">
        <p>
          C2C-CC Release 2 significantly expands the vehicle scope beyond the car-centric Release 1. The
          definition of "vehicle C-ITS station" in RS_OBJ_00149 now explicitly covers:
        </p>

        <CardGrid cols={3}>
          <Card title="Cars &amp; light commercials" accent="brand">
            UNECE categories M1, N1 (passenger cars and vans). The original focus of Release 1; most BSP
            requirements are written for the car case with explicit profile tags.
          </Card>
          <Card title="Trucks &amp; heavy commercials" accent="brand">
            UNECE categories N2 and N3. Platooning and freight use cases; specific CAM profiling for trailer
            length (VehicleLengthConfidenceIndication = trailerPresentWithKnownLength).
          </Card>
          <Card title="Buses" accent="brand">
            UNECE categories M2 and M3; priority-vehicle and public-transport use cases.
          </Card>
          <Card title="Powered Two-Wheelers (PTW)" accent="amber">
            EU Regulation [EU R168] categories L1e-B and L3e. Significant new profiling in R2.0.2: separate
            stationary-speed threshold ({'<='} 1.4 m/s vs {'<='} 0.08 m/s for cars), PTW-specific heading
            latch thresholds, no stored heading at start-up, distinct regular-driving-dynamics bounds (lateral
            acceleration {'<'} 1.9 m/s², longitudinal deceleration {'>'} -2.4 m/s²).
          </Card>
          <Card title="E-bikes &amp; Cycles" accent="amber">
            EPACs ({'≤'} 25 km/h EU), S-EPACs ({'≤'} 45 km/h), throttle-assist bikes. Cycles get a
            dedicated "cycle in use" state machine: detection duration 2 s, timeout 300 s, to prevent CAM
            transmission when the cycle is transported in a car or on a train.
          </Card>
          <Card title="Agricultural &amp; rail" accent="cyan">
            UNECE category T agricultural machines; rail vehicles (trams and urban rail as studied in
            TR 2053). Trailers and drones are listed as "to be decided". Indicates the ambition to cover all
            moving road and track users over successive releases.
          </Card>
        </CardGrid>

        <Callout type="warn" title="Partial implementation is explicitly allowed">
          A vehicle C-ITS station from any category is not required to implement every feature. However,
          if a feature or requirement <em>is</em> implemented, it must be fully compliant with the C2C-CC
          specification — partial compliance of a mandatory requirement is not permitted.
        </Callout>
      </Section>

      {/* ── 12. Protocol stack snapshot ────────────────────────────────────── */}
      <Section id="protocol-stack" title="Protocol Stack as Mandated by the BSP">
        <p>
          The BSP profiles the full <Link to="/architecture">ETSI ITS communications architecture</Link> from
          RF to application. The layer assignments in RS 2037 are:
        </p>

        <LayerStack
          layers={[
            { name: 'Applications / Use Cases', sub: 'Stationary Vehicle, Adverse Weather, PTW, Wrong-way Driver, VRU, CPM, GLOSA …', accent: 'brand' },
            { name: 'Facilities Layer', sub: 'CA Service (CAM · TS 103 900), DEN Service (DENM · TS 103 831), CP Service (CPM), VRU Awareness (VAM)', accent: 'amber' },
            { name: 'Networking & Transport', sub: 'GeoNetworking EN 302 636-4-1 (SHB for CAM, GBC for DENM) · BTP EN 302 636-5-1 (port 2001 CAM, 2002 DENM) · EtherType 0x8947', accent: 'emerald' },
            { name: 'Access Layer', sub: 'ITS-G5 / IEEE 802.11p · EN 302 571 + EN 302 663 · G5-SCH0 5 900 MHz 6 Mbit/s · DCC TS 102 687 · RF 17–33 dBm e.i.r.p.', accent: 'violet' },
            { name: 'Physical / Radio', sub: 'DSRC / ITS-G5 · 5.9 GHz band (5 855–5 925 MHz) · 7 × 10 MHz channels (SCH0–SCH6)', accent: 'rose' },
          ]}
          leftRail="Security (TS 103 097 / CCMS)"
          rightRail="Management (TS 102 941 / Station Mgmt)"
        />
        <p className="mt-4">
          See <Link to="/access-layer">Access Layer</Link> for ITS-G5 channel details,{' '}
          <Link to="/networking">Networking</Link> for GeoNetworking, and{' '}
          <Link to="/security">Security</Link> for the CCMS / PKI layer.
        </p>
      </Section>

      {/* ── 13. Key standards ─────────────────────────────────────────────── */}
      <Section id="key-standards" title="Key Standards and References">
        <Table
          headers={['Document', 'Title', 'Role']}
          rows={[
            [<Ref key="rs2035" code="C2CCC RS 2035" kind="C2CCC" title="Objectives" />, 'C2C-CC Objectives R2.0.2', 'Abstract goals for the vehicle C-ITS station'],
            [<Ref key="rs2036" code="C2CCC RS 2036" kind="C2CCC" title="Features" />, 'C2C-CC Features R2.0.2', 'Feature-level requirements for the vehicle station'],
            [<Ref key="rs2037" code="C2CCC RS 2037" kind="C2CCC" title="Vehicle C-ITS Station Profile" />, 'C2C-CC BSP Profile R2.0.2', 'Normative vehicle C-ITS station profile with numeric parameters'],
            [<Ref key="tr2000" code="C2CCC TR 2000" kind="C2CCC" title="Release Overview" />, 'C2C-CC Release Overview R2.0.2', 'Index of all BSP deliverables and change history'],
            [<Ref key="wp2072" code="C2CCC WP 2072" kind="C2CCC" title="Day 2 Roadmap" />, 'Guidance for Day 2 and Beyond Roadmap v1.2', 'C2C-CC deployment roadmap and enabling concepts'],
            [<Ref key="en302571" code="EN 302 571" kind="ETSI" title="ITS-G5 access layer" />, 'ETSI EN 302 571', 'ITS-G5 (DSRC) access layer standard'],
            [<Ref key="en302663" code="EN 302 663" kind="ETSI" title="ITS-G5 air interface" />, 'ETSI EN 302 663', 'ITS-G5 air interface specification (IEEE 802.11p profile)'],
            [<Ref key="en302636" code="EN 302 636-4-1" kind="ETSI" title="GeoNetworking" />, 'ETSI EN 302 636-4-1', 'GeoNetworking protocol'],
            [<Ref key="ts103900" code="TS 103 900" kind="ETSI" title="CAM" />, 'ETSI TS 103 900', 'Cooperative Awareness Message — Release 2'],
            [<Ref key="ts103831" code="TS 103 831" kind="ETSI" title="DENM" />, 'ETSI TS 103 831', 'DENM — Release 2 GeoNetworking profile'],
            [<Ref key="ts103097" code="TS 103 097" kind="ETSI" title="ITS security" />, 'ETSI TS 103 097', 'ITS security header and certificate formats'],
            [<Ref key="ts102940" code="TS 102 940" kind="ETSI" title="ITS security architecture" />, 'ETSI TS 102 940', 'ITS security architecture and management'],
            [<Ref key="ts102941" code="TS 102 941" kind="ETSI" title="Trust and privacy" />, 'ETSI TS 102 941', 'Trust and privacy management'],
            [<Ref key="ts102687" code="TS 102 687" kind="ETSI" title="DCC" />, 'ETSI TS 102 687', 'Decentralised Congestion Control (DCC)'],
            [<Ref key="en302665" code="EN 302 665" kind="ETSI" title="ITS communications architecture" />, 'ETSI EN 302 665', 'ITS communications architecture — station reference model'],
          ]}
          caption="Normative and informative references underpinning the C2C-CC BSP"
        />
      </Section>

      {/* ── 14. Where next ─────────────────────────────────────────────────── */}
      <Section id="where-next" title="Where Next">
        <CardGrid cols={3}>
          <Card title="C-Roads Platform" accent="emerald" icon="🛣️">
            The road-operator counterpart to C2C-CC — infrastructure C-ITS profiles, RSU deployment, and
            I2V harmonisation.
            <div className="mt-2"><Link to="/c-roads" className="text-brand-300 hover:underline">&#8594; C-Roads page</Link></div>
          </Card>
          <Card title="Access Layer (ITS-G5)" accent="violet" icon="📶">
            Deep-dive into ITS-G5 channels, Decentralised Congestion Control, modulation, and the 5.9 GHz
            spectrum architecture.
            <div className="mt-2"><Link to="/access-layer" className="text-brand-300 hover:underline">&#8594; Access Layer page</Link></div>
          </Card>
          <Card title="Security &amp; PKI" accent="rose" icon="🔐">
            European CCMS, Authorization Tickets, ECDSA P-256, pseudonymisation, and misbehaviour reporting.
            <div className="mt-2"><Link to="/security" className="text-brand-300 hover:underline">&#8594; Security page</Link></div>
          </Card>
          <Card title="Collective Perception (CPM)" accent="brand" icon="👁️">
            Day-2 object sharing — the message that lets a vehicle's radar become a network resource for
            all nearby C-ITS stations.
            <div className="mt-2"><Link to="/cpm" className="text-brand-300 hover:underline">&#8594; CPM page</Link></div>
          </Card>
          <Card title="VRU Awareness (VAM)" accent="amber" icon="🚶">
            Vulnerable Road User C-ITS — pedestrians, cyclists, and PTWs as active C-ITS participants
            broadcasting their presence.
            <div className="mt-2"><Link to="/vam" className="text-brand-300 hover:underline">&#8594; VAM page</Link></div>
          </Card>
          <Card title="Manoeuvre Coordination (MCM)" accent="cyan" icon="🔄">
            Day-3+ cooperative manoeuvring — trajectory sharing and distributed conflict resolution between
            automated vehicles.
            <div className="mt-2"><Link to="/mcm" className="text-brand-300 hover:underline">&#8594; MCM page</Link></div>
          </Card>
        </CardGrid>
      </Section>
    </article>
  )
}
